controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    hexapod_controller:
      type: forward_command_controller/ForwardCommandController

joint_state_broadcaster:
  ros__parameters: {}

hexapod_controller:
  ros__parameters:
    joints:
      - leg_1_hip_joint
      - leg_1_femur_joint
      - leg_1_tibia_joint
      - leg_2_hip_joint
      - leg_2_femur_joint
      - leg_2_tibia_joint
      - leg_3_hip_joint
      - leg_3_femur_joint
      - leg_3_tibia_joint
      - leg_4_hip_joint
      - leg_4_femur_joint
      - leg_4_tibia_joint
      - leg_5_hip_joint
      - leg_5_femur_joint
      - leg_5_tibia_joint
      - leg_6_hip_joint
      - leg_6_femur_joint
      - leg_6_tibia_joint
    interface_name: position
